### ISSUE TITLE
Medical

### ISSUE THREAD

**Issue by m2ura** [reliqui/reliqui#33]
How about you add like payment option for those who have medical, and for those who have cash?
And add medical information, etc...

**Comment by davidhsianturi** [comment]
I think that's a good idea but right now I guess it's not a priority.

**Comment by enzotaufan** [comment]
thanks for your feedback @m2ura we will add the feature in the future we also will add payment with insurance so for the meantime why don't you add Reliqui to your watch list you will receive update about our feature!! hope it helps to answer your question!!
Thanks
