### ISSUE TITLE
Upload & Change Profile Photo

### ISSUE THREAD

**Issue by davidhsianturi** [reliqui/reliqui#35]
It would be nice if users can upload and change their profile photo. we can use the vue-component to handle image uploads or other simple ways and here are some basic behaviors that should occur.

- [ ] users should be login before upload or change their profile photo.
- [ ] authorized users should be able to upload their profile photo.
- [ ] authorized users should be able to change their profile photo.

**Comment by James-N-M** [comment]
I'd like to claim this issue @davidhsianturi  I may need some additional help with this issue
- [ ]  add code links
- [ ]  assign this issue to me

**Comment by davidhsianturi** [comment]
Thanks @James-N-M You're always free to send in a PR!

**Comment by James-N-M** [comment]
@davidhsianturi Hey David, It seems that when I try to open account in the test environment and among others, I get errors such as 
View [partials.master.menu.users.setting] not found. (View: /Users/jamesm/Documents/laravel-sites/reliqui/resources/views/users/settings/account.blade.php)

Let me know if I need to work around this feature that is potentially not implemented or if I just did something wrong in setup

**Comment by davidhsianturi** [comment]
@James-N-M Hi James, looks like there was an error while applying partial path.

**Comment by James-N-M** [comment]
@davidhsianturi Just rebased with upstream master, gonna try again :D !

**Comment by deepu9** [comment]
Not sure whether we are using Spatie Media library, but if anyone has time to look into it, please read the following article
https://laravel-news.com/uploading-avatar-images
Thanks

**Comment by davidhsianturi** [comment]
Yeah, I hear about that package before. and it's a good option.

**Comment by aminraeisi** [comment]
Is this feature added or still missing?
