### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by davidhsianturi** [reliqui/reliqui#36]
Some basic icons should be added to the user interface to indicate their use more clearly.

**Comment by James-N-M** [comment]
@davidhsianturi We may be able to just use some font awesome icons, @davidhsianturi after next Wednesday I should be able to do this.

**Comment by davidhsianturi** [comment]
Hey, @James-N-M font awesome is a good option and very easy to use. ha, is there any way of using font awesome without loading all its icon packs? 
If you're curious, how about using the original SVG and displaying it with laravel blade? so we can use what we want without loading all the icon packs. I found a nice icon here https://github.com/sschoger/heroicons-ui
we can learn some new techniques to solve this issue.

**Comment by James-N-M** [comment]
@davidhsianturi Definitely if it can wait Ill put the research in next week  !
