### ISSUE TITLE
Add first-timers Only Tag

### ISSUE THREAD

**Issue by James-N-M** [reliqui/reliqui#49]
Create a section with a first timers only label for beginner related issues to make commits to this project

**Comment by davidhsianturi** [comment]
hey, @James-N-M do you mean we should add a new label 'first-time'?

**Comment by James-N-M** [comment]
Either add the label or even make a issue that just contains simple simple recommendations for first time pull requests. It’s good for first timer oss contributors and reflects good on your app..
