### ISSUE TITLE
Discuss on Roles and Permissions

### ISSUE THREAD

**Issue by deepu9** [reliqui/reliqui#59]
Hi All,
Can we all discuss Roles and Permissions. I would like everyone to know the list of roles and their permissions in reliqui. This helps us to add authentication and show/hide some sections.

@davidhsianturi can you take the lead and let us know the Roles and Permissions available in Reliqui. Thanks.

**Comment by davidhsianturi** [comment]
Hey, @ deepu9 yes of course. to be able to determine the 'role and permissions' of users in this application, we must first understand the system currently running at the hospital.

from what I know, here's what we can implement.
- Owner: owner of the app (handle all group).
- Administrator: same as an owner just can not invite the user (admin group, staff in group, etc)
- Admin group: admin in each hospital/clinic
- Staff: staff at each hospital/clinic (to validate outpatient while visiting hospital/clinic)
- Doctors: doctors in each hospital/clinic.

Of all these roles, only doctors can have access to view a patient's medical history.

I think this is very simple and meet the needs. however, if there are some other ideas, please feel free to provide the feedback.

**Comment by deepu9** [comment]
Thanks @davidhsianturi for the information.

This is how I see when I say Roles and Permissions:
1. Identify the actors
2. Identify the actions
3. Formulate the relationship between actors and their actions.

**Actors**
Actors are users/people in a business requirement. Following are some of the actors:
- Doctors
- Patients
- Admin
- Staff

Anyone, if you think of any, please add to the above list.

**Actions**
Whatever the actors do in a business requirement. Actions like, have the ability to see patients records, have the ability to register a patient or doctor, have the ability to access everything and soon.

Give me some time to prepare the list of actions.

Meanwhile if anyone has anything to start with, please add them.

**Comment by davidhsianturi** [comment]
Hey, @deepu9 yes, that's a very true basic approach. anyway, 'roles & permissions' must be included in the documentation. we use [gitbook](https://gitbook.com) for write documentation, this weekend I will be working on the basic doc. can I invite you to collaborate?

**Comment by deepu9** [comment]
Sure I'm more than happy to collaborate in writing the docs.
