### ISSUE TITLE
Move features into swim lanes under Projects tab

### ISSUE THREAD

**Issue by deepu9** [reliqui/reliqui#60]
Hi @davidhsianturi,
We can use Projects in github to have features added into swim lanes and anyone can track the status. Please find the screenshots below:
<img width="1006" alt="screen shot 2018-04-03 at 10 20 28 pm" src="https://user-images.githubusercontent.com/3803259/38249008-9573a8d6-378d-11e8-9abb-58d18cbcc23b.png">
<img width="1273" alt="screen shot 2018-04-03 at 10 20 41 pm" src="https://user-images.githubusercontent.com/3803259/38249009-95ac1d24-378d-11e8-946b-cdfe8164115a.png">

Can we move the features list into Projects. Thanks

**Comment by davidhsianturi** [comment]
I think it's readily available. @enzotaufan can you check this one?
