### ISSUE TITLE
Physiotherapy

### ISSUE THREAD

**Issue by m2ura** [reliqui/reliqui#64]
Is it also for physiotherapy, rehabilitation?

**Comment by davidhsianturi** [comment]
No, it's not. do you see that opportunity?

**Comment by m2ura** [comment]
can it maybe be a feature?

**Comment by James-N-M** [comment]
@m2ura maybe fork it and start a new project that can be used a physiotherapy tool. Let me know if you do I'd love to help out.

**Comment by davidhsianturi** [comment]
@m2ura Yes, it's possible. from what I know physiotherapy and rehabilitation is included in outpatient services.
